language: swift
osx_image: xcode9.2

before_install:
- brew install swiftlint
script:
- set -o pipefail && xcodebuild -project Vifra.xcodeproj -scheme Vifra -configuration Release clean build | xcpretty
